# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi_features_C <- function(config, edge_mat, node_par, edge_par, num_params = 0L) {
    .Call(`_CRFutilRcppComponents_phi_features_C`, config, edge_mat, node_par, edge_par, num_params)
}

fix_node_and_edge_par <- function(node_par, edge_par) {
    .Call(`_CRFutilRcppComponents_fix_node_and_edge_par`, node_par, edge_par)
}

fix_node_and_edge_par2 <- function(node_par, edge_par) {
    .Call(`_CRFutilRcppComponents_fix_node_and_edge_par2`, node_par, edge_par)
}

rcpparma_hello_world <- function() {
    .Call(`_CRFutilRcppComponents_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_CRFutilRcppComponents_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_CRFutilRcppComponents_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_CRFutilRcppComponents_rcpparma_bothproducts`, x)
}

